package config

const Host = "host"
const LogLevel = "logLevel"
const StorageDrivers = "storageDrivers"
const VolumeDrivers = "volumeDrivers"
const OsDrivers = "osDrivers"
const MinVolSize = "minVolSize"
const RemoteManagement = "remoteManagement"

const DockerVolumeType = "dockerVolumeType"
const DockerIops = "dockerIops"
const DockerSize = "dockerSize"
const DockerAvailabilityZone = "dockerAvailabilityZone"

const AwsAccessKey = "awsAccessKey"
const AwsSecretKey = "awsSecretKey"
const AwsRegion = "awsRegion"

const RackspaceAuthUrl = "rackspaceAuthUrl"
const RackspaceUserId = "rackspaceUserId"
const RackspaceUserName = "rackspaceUserName"
const RackspacePassword = "rackspacePassword"
const RackspaceTenantId = "rackspaceTenantId"
const RackspaceTenantName = "rackspaceTenantName"
const RackspaceDomainId = "rackspaceDomainId"
const RackspaceDomainName = "rackspaceDomainName"

const ScaleIoEndpoint = "scaleIoEndpoint"
const ScaleIoInsecure = "scaleIoInsecure"
const ScaleIoUseCerts = "scaleIoUseCerts"
const ScaleIoUserName = "scaleIoUserName"
const ScaleIoPassword = "scaleIoPassword"
const ScaleIoSystemId = "scaleIoSystemId"
const ScaleIoSystemName = "scaleIoSystemName"
const ScaleIoProtectionDomainId = "scaleIoProtectionDomainId"
const ScaleIoProtectionDomainName = "scaleIoProtectionDomainName"
const ScaleIoStoragePoolId = "scaleIoStoragePoolId"
const ScaleIoStoragePoolName = "scaleIoStoragePoolName"

const XtremIoEndpoint = "xtremIoEndpoint"
const XtremIoUserName = "xtremIoUserName"
const XtremIoPassword = "xtremIoPassword"
const XtremIoInsecure = "xtremIoInsecure"
const XtremIoDeviceMapper = "xtremIoDeviceMapper"
const XtremIoMultipath = "xtremIoMultipath"
const XtremIoRemoteManagement = "xtremIoRemoteManagement"
